-- Seed script for 20 basket products
-- Run this in Supabase SQL editor

-- Insert basket products
INSERT INTO public.products (
  name,
  slug,
  description,
  short_description,
  price,
  original_price,
  category_id,
  images,
  stock,
  min_stock_level,
  sku,
  weight,
  dimensions,
  tags,
  specifications,
  rating,
  review_count,
  is_featured,
  show_on_homepage,
  is_active,
  meta_title,
  meta_description
) VALUES

-- 1. Classic Willow Basket
(
  'Classic Willow Storage Basket',
  'classic-willow-storage-basket',
  'Beautiful handwoven willow basket perfect for storage and home decor. Made from natural willow branches with a traditional weaving technique. Features a sturdy handle and natural finish. Ideal for organizing textiles, toys, and household items. Each basket is unique with its own character.',
  'Handwoven willow storage basket with handle',
  45.99,
  59.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1595531221060-e4a0a1d9fbee?w=500', 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500'],
  50,
  5,
  'SKU-BASKET-001',
  2.5,
  '{"length": "35cm", "width": "25cm", "height": "20cm"}',
  ARRAY['willow', 'storage', 'handwoven', 'natural'],
  '{"material": "100% Natural Willow", "weaving": "Hand-woven", "handle": "Yes", "finish": "Natural"}',
  4.5,
  24,
  true,
  true,
  true,
  'Classic Willow Storage Basket - Handwoven | Natural Baskets',
  'Premium handwoven willow storage basket. Perfect for home organization. Natural finish, sturdy handle. Buy online.'
),

-- 2. Kangri Mountain Basket
(
  'Kangri Mountain Hand-Woven Basket',
  'kangri-mountain-hand-woven-basket',
  'Inspired by the majestic Kangri mountains, this premium basket features intricate traditional weaving patterns passed down through generations. Crafted from finest quality willow with natural water-resistant finish. Perfect for decorative storage or gifting. Each piece tells a story of mountain craftsmanship.',
  'Premium mountain-inspired handwoven willow basket',
  89.99,
  119.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500', 'https://images.unsplash.com/photo-1595531221060-e4a0a1d9fbee?w=500'],
  30,
  5,
  'SKU-BASKET-002',
  3.2,
  '{"length": "45cm", "width": "35cm", "height": "30cm"}',
  ARRAY['kangri', 'premium', 'mountain', 'handwoven'],
  '{"material": "Premium Willow", "weaving": "Hand-woven", "pattern": "Mountain-inspired", "finish": "Water-resistant"}',
  4.8,
  45,
  true,
  true,
  true,
  'Kangri Mountain Hand-Woven Basket - Premium Quality',
  'Authentic mountain-inspired basket with traditional weaving. Premium willow, water-resistant. Perfect gift.'
),

-- 3. Compact Willow Basket
(
  'Compact Willow Desk Organizer Basket',
  'compact-willow-desk-organizer-basket',
  'Small yet spacious willow basket designed for desk organization. Perfect for organizing office supplies, stationery, or small items. The compact size makes it ideal for shelves and desks. Features a minimalist design that complements modern and traditional interiors alike.',
  'Small handwoven willow basket for desk organization',
  29.99,
  39.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1595531221060-e4a0a1d9fbee?w=500'],
  80,
  10,
  'SKU-BASKET-003',
  1.2,
  '{"length": "20cm", "width": "15cm", "height": "12cm"}',
  ARRAY['compact', 'desk', 'organizer', 'office'],
  '{"material": "Natural Willow", "weaving": "Hand-woven", "handle": "No", "size": "Small"}',
  4.3,
  18,
  false,
  true,
  true,
  'Compact Willow Desk Organizer Basket',
  'Small handwoven willow organizer. Perfect for desk, shelf, office supplies. Minimalist design.'
),

-- 4. Large Family Basket
(
  'Large Family Willow Storage Basket',
  'large-family-willow-storage-basket',
  'Extra-large handwoven willow basket designed for family storage needs. Perfect for storing blankets, pillows, toys, or seasonal items. The generous capacity and sturdy construction make it ideal for hallways, living rooms, and bedrooms. Beautiful enough to display in any room.',
  'Extra-large handwoven willow basket for family storage',
  124.99,
  159.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500', 'https://images.unsplash.com/photo-1595531221060-e4a0a1d9fbee?w=500'],
  25,
  3,
  'SKU-BASKET-004',
  4.5,
  '{"length": "60cm", "width": "45cm", "height": "40cm"}',
  ARRAY['large', 'family', 'storage', 'premium'],
  '{"material": "Premium Willow", "weaving": "Hand-woven", "capacity": "Extra-Large", "handle": "Double handles"}',
  4.7,
  56,
  true,
  true,
  true,
  'Large Family Willow Storage Basket - Premium Quality',
  'Extra-large storage basket, perfect for blankets and toys. Premium handwoven willow.'
),

-- 5. Decorative Wall Basket
(
  'Decorative Willow Wall Display Basket',
  'decorative-willow-wall-display-basket',
  'Artistic handwoven willow basket designed for wall mounting. Features decorative weaving patterns and a modern aesthetic. Perfect for displaying plants, storing decorative items, or creating a focal point on any wall. Includes mounting hardware. A unique piece of functional art.',
  'Wall-mountable decorative willow basket',
  54.99,
  74.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1595531221060-e4a0a1d9fbee?w=500'],
  35,
  5,
  'SKU-BASKET-005',
  1.8,
  '{"length": "40cm", "width": "30cm", "height": "25cm"}',
  ARRAY['decorative', 'wall', 'display', 'art'],
  '{"material": "Natural Willow", "weaving": "Hand-woven", "mounting": "Included", "style": "Modern-traditional"}',
  4.6,
  32,
  true,
  true,
  true,
  'Decorative Willow Wall Display Basket',
  'Beautiful wall-mounted basket with decorative weaving. Includes hardware. Perfect decor.'
),

-- 6. Picnic & Outdoor Basket
(
  'Willow Picnic & Outdoor Basket with Handles',
  'willow-picnic-outdoor-basket-handles',
  'Premium handwoven willow picnic basket ideal for outdoor adventures and family gatherings. Features sturdy double handles and water-resistant natural finish. Perfect for carrying food, drinks, and picnic essentials. The authentic design adds charm to any outdoor occasion.',
  'Handwoven picnic basket with sturdy handles',
  74.99,
  99.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500', 'https://images.unsplash.com/photo-1595531221060-e4a0a1d9fbee?w=500'],
  40,
  5,
  'SKU-BASKET-006',
  2.8,
  '{"length": "50cm", "width": "35cm", "height": "28cm"}',
  ARRAY['picnic', 'outdoor', 'travel', 'portable'],
  '{"material": "Premium Willow", "weaving": "Hand-woven", "handles": "Double", "finish": "Water-resistant"}',
  4.5,
  38,
  true,
  true,
  true,
  'Willow Picnic Basket with Handles - Premium Quality',
  'Authentic picnic basket, water-resistant willow. Perfect for outdoor trips and gatherings.'
),

-- 7. Textile Storage Basket
(
  'Natural Willow Textile Storage Basket',
  'natural-willow-textile-storage-basket',
  'Specially designed willow basket for textile storage. Ideal for organizing clothes, linens, blankets, and fabrics. The open-top design allows easy access while the natural material provides breathability to stored textiles. Perfect for closets, laundry rooms, and bedrooms.',
  'Willow basket optimized for textile and linen storage',
  59.99,
  79.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1595531221060-e4a0a1d9fbee?w=500'],
  45,
  5,
  'SKU-BASKET-007',
  3.0,
  '{"length": "48cm", "width": "38cm", "height": "32cm"}',
  ARRAY['textile', 'storage', 'laundry', 'linen'],
  '{"material": "Natural Willow", "weaving": "Hand-woven", "purpose": "Textile storage", "breathable": true}',
  4.4,
  27,
  false,
  true,
  true,
  'Natural Willow Textile Storage Basket',
  'Perfect for storing textiles, linens, and fabrics. Breathable natural willow construction.'
),

-- 8. Nested Baskets Set
(
  'Handwoven Willow Nested Baskets Set (3 pieces)',
  'handwoven-willow-nested-baskets-set',
  'Beautiful set of three nesting willow baskets in graduated sizes. Perfect for organizing multiple rooms or creating a layered storage solution. Each basket is individually handwoven with consistent quality. Stack them together or display separately. Versatile and space-saving.',
  'Set of 3 handwoven nested willow baskets',
  94.99,
  129.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500', 'https://images.unsplash.com/photo-1595531221060-e4a0a1d9fbee?w=500'],
  20,
  3,
  'SKU-BASKET-008',
  5.5,
  '{"sizes": ["Large", "Medium", "Small"]}',
  ARRAY['nested', 'set', 'space-saving', 'organization'],
  '{"material": "Natural Willow", "pieces": 3, "weaving": "Hand-woven", "stackable": true}',
  4.7,
  42,
  true,
  true,
  true,
  'Willow Nested Baskets Set - 3 Piece Handwoven Collection',
  'Versatile 3-piece basket set. Perfect for organizing any room. Space-saving design.'
),

-- 9. Plant Display Basket
(
  'Willow Plant Display & Pot Basket',
  'willow-plant-display-pot-basket',
  'Elegant willow basket designed specifically for displaying potted plants. Features reinforced bottom and sides to support plant weight safely. Perfect for creating a garden display indoors or on patios. The natural aesthetic complements any plant collection beautifully.',
  'Willow basket for plant pot display and storage',
  49.99,
  69.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1595531221060-e4a0a1d9fbee?w=500'],
  55,
  5,
  'SKU-BASKET-009',
  2.2,
  '{"length": "38cm", "width": "30cm", "height": "26cm", "capacity": "Multiple pots"}',
  ARRAY['plants', 'garden', 'display', 'pots'],
  '{"material": "Reinforced Willow", "weaving": "Hand-woven", "purpose": "Plant display", "reinforced": true}',
  4.5,
  19,
  false,
  true,
  true,
  'Willow Plant Display Basket for Pots',
  'Perfect for displaying potted plants. Reinforced for plant weight. Beautiful garden aesthetic.'
),

-- 10. Artisan Woven Pattern Basket
(
  'Artisan Willow Basket with Complex Weave Pattern',
  'artisan-willow-basket-complex-weave-pattern',
  'Premium handcrafted willow basket featuring intricate and complex weaving patterns created by skilled artisans. Each basket is a unique piece of functional art. Suitable for both storage and display. Perfect gift for those who appreciate traditional craftsmanship.',
  'Artisan-crafted willow basket with intricate weaving',
  99.99,
  139.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500', 'https://images.unsplash.com/photo-1595531221060-e4a0a1d9fbee?w=500'],
  15,
  2,
  'SKU-BASKET-010',
  2.8,
  '{"length": "42cm", "width": "32cm", "height": "28cm"}',
  ARRAY['artisan', 'premium', 'handcrafted', 'pattern'],
  '{"material": "Premium Willow", "weaving": "Complex pattern", "handcrafted": true, "uniqueness": "Each piece unique"}',
  4.9,
  51,
  true,
  true,
  true,
  'Artisan Willow Basket - Complex Weave Pattern',
  'Premium handcrafted basket with intricate patterns. Unique artisan piece. Perfect gift.'
),

-- 11. Natural Undyed Willow Basket
(
  'Natural Undyed Willow Storage Basket',
  'natural-undyed-willow-storage-basket',
  'Pure natural willow basket in its original undyed state. Showcases the beautiful natural color variation of willow wood. Perfect for those preferring authentic, chemical-free storage solutions. The natural finish develops a beautiful patina over time.',
  'Pure natural undyed willow storage basket',
  39.99,
  54.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1595531221060-e4a0a1d9fbee?w=500'],
  60,
  8,
  'SKU-BASKET-011',
  2.4,
  '{"length": "40cm", "width": "30cm", "height": "24cm"}',
  ARRAY['natural', 'undyed', 'eco-friendly', 'organic'],
  '{"material": "100% Natural Willow", "dyed": false, "finish": "Natural patina", "eco-friendly": true}',
  4.4,
  21,
  false,
  true,
  true,
  'Natural Undyed Willow Storage Basket',
  'Pure natural willow, undyed. Eco-friendly storage solution. Beautiful natural finish.'
),

-- 12. Rectangular Utility Basket
(
  'Rectangular Willow Utility Basket',
  'rectangular-willow-utility-basket',
  'Practical rectangular willow basket designed for maximum storage efficiency. The rectangular shape fits perfectly in corners, closets, and shelves. Ideal for organizing linens, clothes, toys, or any household items. Durable and long-lasting construction.',
  'Rectangular handwoven willow utility basket',
  44.99,
  64.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500'],
  70,
  8,
  'SKU-BASKET-012',
  2.6,
  '{"length": "55cm", "width": "30cm", "height": "20cm"}',
  ARRAY['rectangular', 'utility', 'storage', 'practical'],
  '{"material": "Natural Willow", "shape": "Rectangular", "weaving": "Hand-woven", "purpose": "General utility"}',
  4.3,
  15,
  false,
  true,
  true,
  'Rectangular Willow Utility Basket',
  'Practical rectangular basket, fits shelves perfectly. Great for organizing any space.'
),

-- 13. Bedroom Decorative Basket
(
  'Willow Bedroom Decorative & Storage Basket',
  'willow-bedroom-decorative-storage-basket',
  'Beautiful willow basket designed for bedroom use. Combines functionality with aesthetics, perfect for storing blankets, pillows, or clothing while adding warmth to bedroom decor. The neutral natural finish complements any bedroom style.',
  'Decorative willow basket for bedroom storage',
  64.99,
  89.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1595531221060-e4a0a1d9fbee?w=500', 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500'],
  40,
  5,
  'SKU-BASKET-013',
  3.1,
  '{"length": "50cm", "width": "38cm", "height": "32cm"}',
  ARRAY['bedroom', 'decorative', 'textiles', 'home'],
  '{"material": "Premium Willow", "weaving": "Hand-woven", "purpose": "Bedroom storage", "aesthetic": "High"}',
  4.6,
  29,
  true,
  true,
  true,
  'Willow Bedroom Decorative Basket',
  'Beautiful bedroom storage basket. Perfect for blankets and pillows. Premium handwoven willow.'
),

-- 14. Kitchen Counter Basket
(
  'Willow Kitchen Counter Organizer Basket',
  'willow-kitchen-counter-organizer-basket',
  'Compact yet functional willow basket perfect for kitchen counter organization. Ideal for storing fruit, vegetables, cooking utensils, or pantry items. The open design allows quick access to kitchen essentials while keeping counters tidy.',
  'Handwoven willow basket for kitchen organization',
  34.99,
  49.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1595531221060-e4a0a1d9fbee?w=500'],
  75,
  10,
  'SKU-BASKET-014',
  1.9,
  '{"length": "38cm", "width": "28cm", "height": "22cm"}',
  ARRAY['kitchen', 'counter', 'organizer', 'food'],
  '{"material": "Natural Willow", "weaving": "Hand-woven", "purpose": "Kitchen", "open": true}',
  4.5,
  22,
  false,
  true,
  true,
  'Willow Kitchen Counter Organizer Basket',
  'Perfect for kitchen storage. Organize fruit, veggies, utensils. Handwoven willow.'
),

-- 15. Gift Hamper Basket
(
  'Premium Willow Gift Hamper Basket',
  'premium-willow-gift-hamper-basket',
  'Elegant handwoven willow basket designed specifically for gifts and hamper presentations. Features secure handles and beautiful presentation. Perfect for gift-giving occasions or creating custom gift baskets. The quality craftsmanship makes it a gift itself.',
  'Premium gift hamper basket with secure handles',
  84.99,
  114.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500', 'https://images.unsplash.com/photo-1595531221060-e4a0a1d9fbee?w=500'],
  35,
  5,
  'SKU-BASKET-015',
  3.3,
  '{"length": "48cm", "width": "36cm", "height": "30cm"}',
  ARRAY['gift', 'hamper', 'premium', 'occasions'],
  '{"material": "Premium Willow", "weaving": "Hand-woven", "purpose": "Gift presentation", "handles": "Secure"}',
  4.8,
  48,
  true,
  true,
  true,
  'Premium Willow Gift Hamper Basket',
  'Perfect for gift hampers and presentations. Premium quality, secure handles.'
),

-- 16. Round Willow Basket
(
  'Round Handwoven Willow Basket',
  'round-handwoven-willow-basket',
  'Classic round-shaped willow basket offering timeless appeal. Perfect for floor storage, decorative display, or practical organization. The round shape provides excellent capacity while maintaining a compact footprint. Suitable for any room in your home.',
  'Round-shaped handwoven willow storage basket',
  49.99,
  69.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1595531221060-e4a0a1d9fbee?w=500'],
  50,
  6,
  'SKU-BASKET-016',
  2.7,
  '{"diameter": "40cm", "height": "30cm"}',
  ARRAY['round', 'classic', 'storage', 'timeless'],
  '{"material": "Natural Willow", "shape": "Round", "weaving": "Hand-woven", "capacity": "Large"}',
  4.5,
  26,
  false,
  true,
  true,
  'Round Handwoven Willow Basket',
  'Classic round basket, perfect for storage. Handwoven natural willow.'
),

-- 17. Tall Narrow Willow Basket
(
  'Tall Narrow Willow Storage Basket',
  'tall-narrow-willow-storage-basket',
  'Unique tall and narrow willow basket designed for vertical space storage. Perfect for tight corners, narrow shelves, or beside furniture. Ideal for storing rolled items, umbrellas, or tall decorative pieces. Makes efficient use of limited floor space.',
  'Tall narrow willow basket for tight spaces',
  54.99,
  74.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500'],
  45,
  5,
  'SKU-BASKET-017',
  2.4,
  '{"length": "25cm", "width": "25cm", "height": "50cm"}',
  ARRAY['tall', 'narrow', 'space-saving', 'vertical'],
  '{"material": "Natural Willow", "shape": "Tall-narrow", "purpose": "Vertical storage", "space-efficient": true}',
  4.3,
  17,
  false,
  true,
  true,
  'Tall Narrow Willow Storage Basket',
  'Perfect for tight spaces. Ideal for vertical storage. Space-efficient design.'
),

-- 18. Shallow Display Basket
(
  'Shallow Willow Display Basket',
  'shallow-willow-display-basket',
  'Shallow and wide willow basket perfect for display purposes. Ideal for presenting decorative items, plants, or collectibles. The shallow design ensures contents remain visible while the wide surface area provides excellent display opportunity. Perfect for shelving and mantels.',
  'Shallow willow basket for decorative display',
  39.99,
  59.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1595531221060-e4a0a1d9fbee?w=500'],
  60,
  8,
  'SKU-BASKET-018',
  1.8,
  '{"length": "50cm", "width": "40cm", "height": "15cm"}',
  ARRAY['display', 'shallow', 'decorative', 'showcase'],
  '{"material": "Natural Willow", "shape": "Shallow-wide", "purpose": "Display", "visible": true}',
  4.4,
  20,
  false,
  true,
  true,
  'Shallow Willow Display Basket',
  'Perfect for displaying plants, decor, and collectibles. Shallow design for visibility.'
),

-- 19. Professional Grade Willow Basket
(
  'Professional Grade Willow Storage Basket',
  'professional-grade-willow-storage-basket',
  'Heavy-duty professional-grade willow basket built for demanding use. Reinforced construction ensures durability in commercial or intensive home use. Perfect for businesses, studios, or households needing maximum durability. Maintains quality through heavy use.',
  'Heavy-duty professional grade willow storage basket',
  109.99,
  149.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500', 'https://images.unsplash.com/photo-1595531221060-e4a0a1d9fbee?w=500'],
  20,
  3,
  'SKU-BASKET-019',
  4.2,
  '{"length": "55cm", "width": "45cm", "height": "38cm"}',
  ARRAY['professional', 'heavy-duty', 'reinforced', 'durable'],
  '{"material": "Reinforced Premium Willow", "grade": "Professional", "durability": "Extra-heavy", "reinforced": true}',
  4.7,
  34,
  true,
  true,
  true,
  'Professional Grade Willow Storage Basket - Heavy-Duty',
  'Heavy-duty basket for commercial or intensive use. Professional-grade quality.'
),

-- 20. Seasonal Holiday Basket
(
  'Willow Holiday & Seasonal Decoration Basket',
  'willow-holiday-seasonal-decoration-basket',
  'Beautiful willow basket designed for seasonal storage and holiday decoration. Perfect for storing and displaying seasonal decorations, holiday items, or themed decorative pieces. The natural aesthetic complements seasonal decor beautifully throughout the year.',
  'Willow basket for holiday and seasonal storage',
  69.99,
  94.99,
  NULL,
  ARRAY['https://images.unsplash.com/photo-1595531221060-e4a0a1d9fbee?w=500', 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500'],
  40,
  5,
  'SKU-BASKET-020',
  3.2,
  '{"length": "48cm", "width": "38cm", "height": "32cm"}',
  ARRAY['holiday', 'seasonal', 'decoration', 'festive'],
  '{"material": "Premium Willow", "weaving": "Hand-woven", "purpose": "Seasonal storage", "aesthetic": "Festive"}',
  4.6,
  31,
  true,
  true,
  true,
  'Willow Holiday Basket - Seasonal Decoration Storage',
  'Perfect for storing holiday decorations. Beautiful seasonal storage solution.'
);

-- Verify the insertion
SELECT COUNT(*) as total_baskets FROM public.products WHERE tags @> ARRAY['willow'] OR tags @> ARRAY['basket'];
